[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx medusa migrations run && npm run start'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
